#spring.application.name=smartemployee
#server.port=8084
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/smartEmployee
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true

spring.application.name=smartemployee
server.port=8084
 
# Use Render Database URL
spring.datasource.url=${DATABASE_URL}
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
 